routes/admin.php
<?php

use App\Http\Controllers\Admin\Auth\AdminLoginController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\MediaManagerController;
use App\Http\Controllers\Admin\UserDataController; 

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['XSS', 'HtmlSpecialchars']], function () {
    Route::get('lang', function () {
        generateLangFrontend('views/frontend', 'lang/en/frontend.php');
        generateLangBackend('views/admin', 'lang/en/admin.php');
    });
    // Admin Routes
    Route::get('/login',   [AdminLoginController::class, 'adminLoginForm'])->name('admin.login');
    Route::post('/login',  [AdminLoginController::class, 'adminCheckLogin'])->name('admin.login');
    Route::post('/logout', [AdminLoginController::class, 'adminLogout'])->name('admin.logout');

    Route::group(['as' => 'admin.', 'middleware' => 'auth:admin'], function () {
        // Dashoboard
        Route::get('/',          [DashboardController::class, 'index'])->name('dashboard');
        Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
        //Media Manager Routes
        Route::get('/showmanager',          [MediaManagerController::class, 'showmanager'])->name('showmanager');
        Route::get('/mediamanager',         [MediaManagerController::class, 'index'])->name('mediamanager');
        Route::post('/mediamanager/upload', [MediaManagerController::class, 'upload'])->name('mediaupload');
        Route::get('/mediamanager/images',  [MediaManagerController::class, 'images'])->name('mediaimages');
        Route::get('/mediamanager/delete/', [MediaManagerController::class, 'delete'])->name('media.delete');

        Route::get('/settings',             [SettingsController::class,     'settings'])->name('settings');
        Route::resource('roles', App\Http\Controllers\Admin\RoleController::class);
        // Settings Routes
        Route::get('/contact-message',      [SettingsController::class, 'contact_message'])->name('contact_message');
        Route::put('/genral/settings',      [SettingsController::class, 'savegeneralsettings'])->name('generalsettings');
        Route::put('/pagination/settings',      [SettingsController::class, 'paginationsettings'])->name('paginationsettings');
        Route::put('/cookie/settings',      [SettingsController::class, 'savecookiesettings'])->name('cookiesettings');
        Route::put('/payment/settings',     [SettingsController::class, 'savepaymentsettings'])->name('paymentsettings');
        Route::put('/email/settings',       [SettingsController::class, 'savemailsettings'])->name('mailsettings');
        Route::put('/google-map/settings',  [SettingsController::class, 'mapsettings'])->name('mapsettings');

        Route::get('/reset',      [UserDataController::class, 'reset'])->name('reset');
        Route::get('/backup',      [UserDataController::class, 'backup'])->name('backup');
        Route::post('/restore',     [UserDataController::class, 'restore'])->name('restore');
        Route::get('/maintenance',      [UserDataController::class, 'maintenance_mode'])->name('maintenance');
        Route::resource('page-preview',   App\Http\Controllers\Admin\PagePreviewController::class);
        // Localization
        Route::resource('frontend-language',   App\Http\Controllers\Admin\FrontendLanguageController::class);
        Route::resource('admin-language',   App\Http\Controllers\Admin\AdminLanguageController::class);
        // Email
        Route::resource('email-template', App\Http\Controllers\Admin\EmailTemplateController::class);
        Route::resource('subscriber',     App\Http\Controllers\Admin\SubscriberController::class);
        Route::resource('send-email',     App\Http\Controllers\Admin\SendEmailController::class);
        // Blog
        Route::resource('blog',            App\Http\Controllers\Admin\BlogController::class);
        Route::resource('blog-category',   App\Http\Controllers\Admin\BlogCategoryController::class);
        Route::resource('blog-comment',    App\Http\Controllers\Admin\BlogCommentController::class);
        Route::resource('contact-messages', App\Http\Controllers\Admin\ContactMessageController::class);
        // Components
        Route::resource('slider',           App\Http\Controllers\Admin\SliderController::class);
        Route::resource('faq',              App\Http\Controllers\Admin\FaqController::class);
        Route::resource('service',          App\Http\Controllers\Admin\ServiceController::class);
        Route::resource('testimonial',      App\Http\Controllers\Admin\TestimonialController::class);
        Route::resource('about',            App\Http\Controllers\Admin\AboutController::class);
        Route::resource('trainer',          App\Http\Controllers\Admin\TrainerController::class);
        Route::resource('sectitontitle',    App\Http\Controllers\Admin\SectionTitleController::class);
        Route::resource('ourprocess',      App\Http\Controllers\Admin\OurProcessController::class);
        // Shop
        Route::resource('course', App\Http\Controllers\Admin\CourseController::class);
        Route::resource('coursecategory', App\Http\Controllers\Admin\CoursecategoryController::class);
        Route::resource('product',          App\Http\Controllers\Admin\ProductController::class);
        Route::resource('product-review',   App\Http\Controllers\Admin\ProductReviewController::class);
        Route::resource('product-category', App\Http\Controllers\Admin\ProductCategoryController::class);
        Route::resource('order',            App\Http\Controllers\Admin\OrderController::class);
        Route::resource('transaction',      App\Http\Controllers\Admin\TransactionController::class);

        Route::resource('shipping', App\Http\Controllers\Admin\ShippingController::class);
        Route::resource('shop-setting',     App\Http\Controllers\Admin\ShopSettingController::class);
        Route::resource('shipping-country', App\Http\Controllers\Admin\ShippingCountryController::class);
        Route::resource('coupon', App\Http\Controllers\Admin\CouponController::class);
        // Footer
        Route::resource('social-link',         App\Http\Controllers\Admin\SocialLinkController::class);
        Route::resource('footer-contact-item', App\Http\Controllers\Admin\FooterContactItemController::class);

        Route::resource('terms-of-use',      App\Http\Controllers\Admin\TermsOfUseController::class);
        Route::resource('privacy-policy',    App\Http\Controllers\Admin\PrivacyPolicyController::class);
        Route::resource('user-profile',      App\Http\Controllers\Admin\UserProfileController::class);
        Route::resource('users', App\Http\Controllers\Admin\UserController::class); 
    });
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\Auth\ResetPasswordController;
use App\Http\Controllers\Frontend\Authr\ForgotPasswordController;
use App\Http\Controllers\Frontend\DynamicPageController;
use App\Http\Controllers\Frontend\ShopController;
use App\Http\Controllers\Frontend\UserPanelController;
use App\Http\Controllers\Frontend\Auth\UserLoginController;
use App\Http\Controllers\Frontend\Auth\UserRegisterController;
use App\Http\Controllers\Frontend\PaymentController;
use App\Http\Controllers\Frontend\PaypalController;
use App\Http\Controllers\Frontend\Auth\VerificationController;
use App\Http\Controllers\Frontend\SslCommerzPaymentController;
use App\Http\Controllers\User\MediaManagerController as UserMediaManagerController;
use App\Http\Controllers\User\TransactionController as UserTransactionController;
use App\Http\Controllers\User\UserOrderController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['XSS', 'HtmlSpecialchars']], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/email/verify', [VerificationController::class, 'show'])->name('verification.notice');
        Route::get('/email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify')->middleware(['signed']);
        Route::post('/email/resend', [VerificationController::class, 'resend'])->name('verification.resend');
    });
    // Frontend
    Route::get('/subscribe',                [App\Http\Controllers\Frontend\EmailTemplateController::class, 'subscription'])->name('subscribe');
    Route::get('/verify/{email}',                [App\Http\Controllers\Frontend\EmailTemplateController::class, 'verify'])->name('verify');

    Route::get('/',                     [DynamicPageController::class,  'index'])->name('home');
    Route::get('/about',                     [DynamicPageController::class,  'about'])->name('about');
    Route::get('/contact',                     [DynamicPageController::class,  'contact'])->name('contact');
    Route::get('/services',                     [DynamicPageController::class,  'services'])->name('services');
    Route::get('/signin',                     [DynamicPageController::class,  'signin'])->name('signin');
    Route::get('/term-condition',                     [DynamicPageController::class,  'termcondition'])->name('termcondition');
    Route::get('/faq',                     [DynamicPageController::class,  'faq'])->name('faq');
    Route::get('/privacy',                     [DynamicPageController::class,  'privacy'])->name('privacy');
    Route::get('/bloglist',                     [DynamicPageController::class,  'bloglist'])->name('bloglist');
    Route::get('/blog-details',                     [DynamicPageController::class,  'blogdetails'])->name('blogdetails');
    Route::get('/course/details/{slug}', [App\Http\Controllers\Frontend\CourseController::class,  'show'])->name('course.show');
    Route::get('/course', [App\Http\Controllers\Frontend\CourseController::class,  'index'])->name('course.index');

    //billing
    Route::get('/checkout',                     [App\Http\Controllers\Frontend\BillingController::class,  'checkout'])->middleware('auth')->name('checkout');
    Route::get('/coupon-apply',                     [App\Http\Controllers\Frontend\BillingController::class,  'couponapply'])->name('couponapply');
    Route::get('/cart-view',                     [App\Http\Controllers\Frontend\BillingController::class,  'cartview'])->name('cartview');
    Route::get('/add-to-cart',  [App\Http\Controllers\Frontend\BillingController::class, 'addcart'])->name('addcart');
    Route::get('/remove-from-cart', [App\Http\Controllers\Frontend\BillingController::class, 'removecart'])->name('removecart');
    Route::post('/proceed/checkout', [App\Http\Controllers\Frontend\BillingController::class, 'proceedcheckout'])->name('proceedcheckout');
    Route::group(['middleware' => ['auth', 'verified']], function() {
        Route::post('/freepurches', [App\Http\Controllers\Frontend\PaymentController::class,  'freepurches'])->name('freepurches');
        Route::get('/payment',                     [App\Http\Controllers\Frontend\BillingController::class,  'payment'])->name('payment');
    });
    Route::post('/placeorder', [App\Http\Controllers\Frontend\BillingController::class, 'placeorder'])->name('placeorder');

    Route::get('product/{slug}', [App\Http\Controllers\frontend\ProductController::class, 'show'])->name('product.show');
    Route::resource('/product', App\Http\Controllers\Frontend\ProductController::class);
    Route::get('/productsearch', [App\Http\Controllers\Frontend\ProductController::class, 'searchproduct'])->name('productsearch');
    Route::get('blog/{slug}', [App\Http\Controllers\frontend\BlogController::class, 'show'])->name('blog.show');
    Route::resource('blog', App\Http\Controllers\Frontend\BlogController::class);
    Route::post('blogcomment', [App\Http\Controllers\Frontend\BlogCommentController::class, 'store'])->name('blogcomment.store');
    Route::resource('contactmessage', App\Http\Controllers\Frontend\ContactMessageController::class);

    Route::get('cart-page',             [ShopController::class,     'cart_page'])->name('cart_page');
    // // Login Routes
    Route::get('login',                     [UserLoginController::class,  'userLoginForm'])->name('user.login');
    Route::post('/login',               [UserLoginController::class,    'userCheckLogin'])->name('user.login');
    Route::resource('registrations', UserRegisterController::class);
    Route::post('/logout',              [UserLoginController::class,    'userLogout'])->name('user.logout');
    Route::get('/forgot',               [ForgotPasswordController::class, 'forgot'])->name('user.forgot');
    Route::post('/forgot',              [ForgotPasswordController::class, 'resetLink'])->name('user.forgot');
    Route::get('/password-reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('user.reset');
    Route::post('/password-reset',      [ResetPasswordController::class, 'resetPassword'])->name('user.reset');
    Route::get('{slug}',                [DynamicPageController::class, 'page'])->name ('page');
 
    Route::group(['as' => 'user.','middleware' => ['auth', 'verified'], 'prefix' => 'user'], function () {
        Route::get('/mediamanager',         [UserMediaManagerController::class, 'index'])->name('mediamanager');
        Route::post('/mediamanager/upload', [UserMediaManagerController::class, 'upload'])->name('mediaupload');
        Route::get('/mediamanager/images',  [UserMediaManagerController::class, 'images'])->name('mediaimages');
        Route::get('/mediamanager/delete/', [UserMediaManagerController::class, 'delete'])->name('media.delete');
        Route::post('/productreview', [App\Http\Controllers\Frontend\ProductReviewController::class, 'store'])->name('productreview');
        Route::post('/coursereview', [App\Http\Controllers\Frontend\CourseReviewController::class, 'store'])->name('coursereview');
        Route::get('shop/cart',         [ShopController::class,      'cart'])->name('cart');
        Route::post('/update-profile',  [UserPanelController::class, 'update_profile'])->name('update');
        Route::post('/shipping-address',  [UserPanelController::class, 'shipping_address'])->name('shipping-address');
        Route::get('/dashboard',        [UserPanelController::class, 'dashboard'])->name('dashboard');
        Route::get('/profile',          [UserPanelController::class, 'profile'])->name('profile');
        Route::post('/updateprofile',  [UserPanelController::class, 'store'])->name('updateprofile'); 
        Route::post('/updateaddress',  [UserPanelController::class, 'update_address'])->name('updateaddress');
        Route::resource('order',            UserOrderController::class);
        Route::get('transactions',     [UserTransactionController::class, 'index'])->name('transactions');

        Route::post('/sslcommerz-pay',    [SslCommerzPaymentController::class, 'index'])->name('sslcommerz-pay');
        Route::post('/sslcommerz-pay-via-ajax', [SslCommerzPaymentController::class, 'payViaAjax'])->name('sslcommerz-pay-ajax');
        Route::post('/sslcommerz-success', [SslCommerzPaymentController::class,   'success'])->name('sslcommerz-success');
        Route::post('/sslcommerz-failed', [SslCommerzPaymentController::class,   'fail'])->name('sslcommerz-failed');
        Route::post('/sslcommerz-cancel', [SslCommerzPaymentController::class,   'cancel'])->name('sslcommerz-cancel');
        Route::post('/sslcommerz-ipn', [SslCommerzPaymentController::class, 'ipn'])->name('sslcommerz-ipn');

        Route::get('/pay-with-paypal',       [PaypalController::class,   'paypal_pay'])->name('pay-with-paypal');
        Route::get('/paypal-payment-success',       [PaypalController::class,   'paypal_success'])->name('paypal-payment-success');
        Route::get('/paypal-payment-cancled',       [PaypalController::class,   'paypal_cancel'])->name('paypal-payment-cancled');

        Route::post('/bank-pay',        [PaymentController::class,   'bank'])->name('bank-pay');
        Route::post('/stripe-pay',      [PaymentController::class,   'stripe'])->name('stripe-pay');
        Route::post('/razorpay-pay',    [PaymentController::class,   'razorpay'])->name('razorpay-pay');
        Route::post('/mollie-pay',      [PaymentController::class,   'mollie'])->name('mollie-pay');
        Route::get('/mollie-notify',    [PaymentController::class,   'mollie_notify'])->name('mollie-notify');
        Route::post('/instamojo-pay',   [PaymentController::class,   'instamojo'])->name('instamojo-pay');
        Route::get('/instamojo-verify', [PaymentController::class,   'instamojo_verify'])->name('instamojo-verify');
        Route::get('/paystack-pay',     [PaymentController::class,   'paystack'])->name('paystack-pay');

resources/views/admin/layouts/sidebar/basic.blade.php
<li class="{{request()->routeIs('admin.dashboard') ? 'active': ''}}">
    <a class="nav-link" href="{{ route('admin.dashboard') }}">
        <i class="fas fa-fire"></i>
        <span>{{__('admin.Dashboard')}}</span>
    </a>
</li>
@canany(['blog-index', 'blog-create', 'blog-category-index', 'blog-comment-index'])
    <li class="nav-item dropdown {{request()->is('admin/blog*') ? 'active': ''}}">
        <a href="#" class="nav-link has-dropdown">
            <i class="fas fa-edit"></i><span>{{__('admin.Blog')}}</span>
        </a>
        <ul class="dropdown-menu">
            @can('blog-category-index')
                <li class="{{(request()->routeIs('admin.blog-category.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.blog-category.index') }}">{{__('admin.Categories')}}</a>
                </li>
            @endcan
            @can('blog-index')
                <li class="{{(request()->routeIs('admin.blog.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.blog.index') }}">{{__('admin.Blogs')}}</a>
                </li>
            @endcan
            @can('blog-comment-index')
                <li class="{{(request()->routeIs('admin.blog-comment.index')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.blog-comment.index') }}">{{__('admin.Comments')}}</a>
                </li>
            @endcan
        </ul>
    </li>
@endcanany 
@canany(['course-index', 'course-create', 'course-edit', 'course-delete'])
    <li class="nav-item dropdown {{request()->is('admin/course*') ? 'active': ''}}">
        <a href="#" class="nav-link has-dropdown">
            <i class="fas fa-edit"></i><span>{{__('Courses')}}</span>
        </a>
        <ul class="dropdown-menu">
            @can('course-category-index')
                <li class="{{(request()->routeIs('admin.coursecategory.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.coursecategory.index') }}">{{__('Category List')}}</a>
                </li>
            @endcan
            @can('course-index')
                <li class="{{(request()->routeIs('admin.course.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.course.index') }}">{{__('List')}}</a>
                </li>
            @endcan
        </ul>
    </li>
@endcanany
@canany(['about-index', 'faq-index', 'terms-of-use-index', 'privacy-policy-index'])
    <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown"> 
            <i class="fas fa-copy"></i><span>{{__('admin.Pages')}}</span>
        </a>
        <ul class="dropdown-menu">
            @can('about-index')
                <li class="{{(request()->routeIs('admin.about.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.about.index') }}">{{__('admin.About')}}</a>
                </li>
            @endcan
            @can('faq-index')
                <li class="{{(request()->routeIs('admin.faq.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.faq.index') }}">{{__('admin.Faq')}}</a>
                </li>
            @endcan
            @can('terms-of-use-index')
                <li class="{{(request()->routeIs('admin.terms-of-use.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.terms-of-use.index') }}">{{__('admin.Terms of use')}}</a>
                </li>
            @endcan
            @can('privacy-policy-index')
                <li class="{{(request()->routeIs('admin.privacy-policy.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.privacy-policy.index') }}">{{__('admin.Privacy policy')}}</a>
                </li>
            @endcan
        </ul>
    </li>
@endcanany
<li class="nav-item dropdown ">
    <a href="#" class="nav-link has-dropdown"> 
        <i class="fas fa-puzzle-piece"></i><span>{{__('Home Sections')}}</span>
    </a>
    <ul class="dropdown-menu">
        <li class="{{(request()->routeIs('admin.trainer.*')) ? 'active': ''}}">
            <a href="{{ route('admin.trainer.index') }}" class="nav-link">
                {{__('Trainer')}}
            </a>
        </li>
        @can('ourprocess-index')
            <li class="{{(request()->routeIs('admin.ourprocess.*')) ? 'active': ''}}">
                <a href="{{ route('admin.ourprocess.index') }}" class="nav-link">
                    {{__('Our Process')}}
                </a>
            </li>
        @endcan
        @can('sectiontitle-index')
            <li class="{{(request()->routeIs('admin.sectitontitle.*')) ? 'active': ''}}">
                <a href="{{ route('admin.sectitontitle.index') }}" class="nav-link">
                    {{__('Others')}}
                </a>
            </li>
        @endcan
    </ul>
</li>
@canany(['product-index', 'product-category-index', 'order-index', 'product-review-index', 'shop-discount-index', 'transaction-index',
                'shipping-country-index', 'shop-settings-index'])
    <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown">
            <i class="fas fa-store"></i><span>{{__('admin.Shop')}}</span>
        </a>
        <ul class="dropdown-menu">
            @can('product-index')
                <li class="{{(request()->routeIs('admin.product.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.product.index') }}">{{__('admin.Products')}}</a>
                </li>
            @endcan
            @can('product-category-index')
                <li class="{{(request()->routeIs('admin.product-category.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.product-category.index') }}">{{__('admin.Categories')}}</a>
                </li>
            @endcan
            @can('order-index')
                <li class="{{(request()->routeIs('admin.order.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.order.index') }}">{{__('admin.Orders')}}</a>
                </li>
            @endcan
            @can('product-review-index')
                <li class="{{(request()->routeIs('admin.product-review.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.product-review.index') }}">{{__('admin.Reviews')}}</a>
                </li>
            @endcan
            @can('transaction-index')
                <li class="{{(request()->routeIs('admin.transaction.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.transaction.index') }}">{{__('admin.Transactions')}}</a>
                </li>
            @endcan
            @can('shipping-country-index')
                <li class="{{(request()->routeIs('admin.shipping-country.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.shipping-country.index') }}">{{__('admin.Shipping country')}}</a>
                </li>
            @endcan
            <li class="{{(request()->routeIs('admin.shipping.*')) ? 'active': ''}}">
                <a class="nav-link" href="{{ route('admin.shipping.index') }}">{{__('Shipping Cost')}}</a>
            </li>
            <li class="{{(request()->routeIs('admin.coupon.*')) ? 'active': ''}}">
                <a class="nav-link" href="{{ route('admin.coupon.index') }}">{{__('Coupon')}}</a>
            </li>
            @can('shop-settings-index')
                <li class="{{(request()->routeIs('admin.shop-setting.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.shop-setting.index') }}">{{__('admin.Shop setting')}}</a>
                </li>
            @endcan
        </ul>
    </li>
@endcanany
@can('contact-message-index')
    <li class="{{(request()->routeIs('admin.contact-messages.*')) ? 'active': ''}}">
        <a class="nav-link" href="{{ route('admin.contact-messages.index') }}"><i class="fas fa-comment"></i>
            <span>{{__('admin.Contact Messages')}}</span>
        </a>
    </li>
@endcan

resources/views/admin/layouts/sidebar/content.blade.php
@canany(['testimonial-index', 'service-index', 'slider-index', 'sponsor-index'])
    @can('testimonial-index')
        <li class="nav-item {{(request()->routeIs('admin.testimonial.*')) ? 'active': ''}}">
            <a href="{{ route('admin.testimonial.index') }}" class="nav-link">
                <i class="fas fa-comments"></i><span>{{__('admin.Testimonials')}}</span>
            </a>
        </li>
    @endcan
    @can('service-index')
        <li class="nav-item {{(request()->routeIs('admin.service.*')) ? 'active': ''}}">
            <a href="{{ route('admin.service.index') }}" class="nav-link">
                <i class="fas fa-cogs"></i><span>{{__('admin.Services')}}</span>
            </a>
        </li>
    @endcan
    @can('slider-index')
        <li class="nav-item {{(request()->routeIs('admin.slider.*')) ? 'active': ''}}">
            <a href="{{ route('admin.slider.index') }}" class="nav-link">
                <i class="fas fa-sliders-h"></i><span>{{__('admin.Slider')}}</span>
            </a>
        </li>
    @endcan
@endcanany
@canany(['footer-contact-item-index', 'footer-information-index', 'social-link-index'])
    <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown">
            <i class="fas fa-edit"></i><span>{{__('admin.Footer')}}</span>
        </a>
        <ul class="dropdown-menu">
            @can('footer-contact-item-index')
                <li class="{{(request()->routeIs('admin.footer-contact-item.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.footer-contact-item.index') }}">
                        {{trans('admin.Contact')}}
                    </a>
                </li>
            @endcan
            @can('social-link-index')
                <li class="{{(request()->routeIs('admin.social-link.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.social-link.index') }}">
                        {{trans('Social media')}}
                    </a>
                </li>
            @endcan
        </ul>
    </li>
@endcanany
@canany(['admin-language-index', 'frontend-language-index'])
    <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown"> 
            <i class="fas fa-globe-asia"></i><span>{{__('admin.Language')}}</span>
        </a>
        <ul class="dropdown-menu">
            @can('frontend-language-index')
                <li class="{{(request()->routeIs('admin.frontend-language.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.frontend-language.index') }}">
                        {{trans('admin.Frontend')}}
                    </a>
                </li>
            @endcan
            @can('admin-language-index')
                <li class="{{(request()->routeIs('admin.admin-language.*')) ? 'active': ''}}">
                    <a class="nav-link" href="{{ route('admin.admin-language.index') }}">
                        {{trans('admin.Admin')}}
                    </a>
                </li>
            @endcan
        </ul>
    </li>
@endcanany

resources/views/admin/layouts/sidebar/index.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand px-5 mb-4">
            <a href="{{ url('/admin/dashboard') }}">
                <img class="w-100 mt-2" src="{{ url(GetSetting('site_logo')) }}">
            </a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ url('/admin/dashboard') }}">
                <img src="{{ url(GetSetting('site_favicon')) }}">
            </a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">{{__('admin.Basics')}}</li>
            @include('admin.layouts.sidebar.basic')
            <li class="menu-header">{{__('admin.Contents')}}</li>
            @include('admin.layouts.sidebar.content')
            <li class="menu-header">{{__('admin.Tools')}}</li>
            @include('admin.layouts.sidebar.tool')
        </ul>
    </aside>
</div>