routes/admin.php
<?php

use App\Http\Controllers\Admin\Auth\AdminLoginController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\MediaManagerController;
use App\Http\Controllers\Admin\UserDataController; 

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['XSS', 'HtmlSpecialchars']], function () {
    Route::get('lang', function () {
        generateLangFrontend('views/frontend', 'lang/en/frontend.php');
        generateLangBackend('views/admin', 'lang/en/admin.php');
    });
    // Admin Routes
    Route::get('/login',   [AdminLoginController::class, 'adminLoginForm'])->name('admin.login');
    Route::post('/login',  [AdminLoginController::class, 'adminCheckLogin'])->name('admin.login');
    Route::post('/logout', [AdminLoginController::class, 'adminLogout'])->name('admin.logout');

    Route::group(['as' => 'admin.', 'middleware' => 'auth:admin'], function () {
        // Dashoboard
        Route::get('/',          [DashboardController::class, 'index'])->name('dashboard');
        Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
        //Media Manager Routes
        Route::get('/showmanager',          [MediaManagerController::class, 'showmanager'])->name('showmanager');
        Route::get('/mediamanager',         [MediaManagerController::class, 'index'])->name('mediamanager');
        Route::post('/mediamanager/upload', [MediaManagerController::class, 'upload'])->name('mediaupload');
        Route::get('/mediamanager/images',  [MediaManagerController::class, 'images'])->name('mediaimages');
        Route::get('/mediamanager/delete/', [MediaManagerController::class, 'delete'])->name('media.delete');

        Route::get('/settings',             [SettingsController::class,     'settings'])->name('settings');
        Route::resource('roles', App\Http\Controllers\Admin\RoleController::class);
        // Settings Routes
        Route::get('/contact-message',      [SettingsController::class, 'contact_message'])->name('contact_message');
        Route::put('/genral/settings',      [SettingsController::class, 'savegeneralsettings'])->name('generalsettings');
        Route::put('/pagination/settings',      [SettingsController::class, 'paginationsettings'])->name('paginationsettings');
        Route::put('/cookie/settings',      [SettingsController::class, 'savecookiesettings'])->name('cookiesettings');
        Route::put('/payment/settings',     [SettingsController::class, 'savepaymentsettings'])->name('paymentsettings');
        Route::put('/email/settings',       [SettingsController::class, 'savemailsettings'])->name('mailsettings');
        Route::put('/google-map/settings',  [SettingsController::class, 'mapsettings'])->name('mapsettings');

        Route::get('/reset',      [UserDataController::class, 'reset'])->name('reset');
        Route::get('/backup',      [UserDataController::class, 'backup'])->name('backup');
        Route::post('/restore',     [UserDataController::class, 'restore'])->name('restore');
        Route::get('/maintenance',      [UserDataController::class, 'maintenance_mode'])->name('maintenance');
        Route::resource('page-preview',   App\Http\Controllers\Admin\PagePreviewController::class);
        // Localization
        Route::resource('frontend-language',   App\Http\Controllers\Admin\FrontendLanguageController::class);
        Route::resource('admin-language',   App\Http\Controllers\Admin\AdminLanguageController::class);
        // Email
        Route::resource('email-template', App\Http\Controllers\Admin\EmailTemplateController::class);
        Route::resource('subscriber',     App\Http\Controllers\Admin\SubscriberController::class);
        Route::resource('send-email',     App\Http\Controllers\Admin\SendEmailController::class);
        // Blog
        Route::resource('blog',            App\Http\Controllers\Admin\BlogController::class);
        Route::resource('blog-category',   App\Http\Controllers\Admin\BlogCategoryController::class);
        Route::resource('blog-comment',    App\Http\Controllers\Admin\BlogCommentController::class);
        Route::resource('contact-messages', App\Http\Controllers\Admin\ContactMessageController::class);
        // Components
        Route::resource('slider',           App\Http\Controllers\Admin\SliderController::class);
        Route::resource('faq',              App\Http\Controllers\Admin\FaqController::class);
        Route::resource('service',          App\Http\Controllers\Admin\ServiceController::class);
        Route::resource('testimonial',      App\Http\Controllers\Admin\TestimonialController::class);
        Route::resource('about',            App\Http\Controllers\Admin\AboutController::class);
        Route::resource('trainer',          App\Http\Controllers\Admin\TrainerController::class);
        Route::resource('sectitontitle',    App\Http\Controllers\Admin\SectionTitleController::class);
        Route::resource('ourprocess',      App\Http\Controllers\Admin\OurProcessController::class);
        // Shop
        Route::resource('course', App\Http\Controllers\Admin\CourseController::class);
        Route::resource('coursecategory', App\Http\Controllers\Admin\CoursecategoryController::class);
        Route::resource('product',          App\Http\Controllers\Admin\ProductController::class);
        Route::resource('product-review',   App\Http\Controllers\Admin\ProductReviewController::class);
        Route::resource('product-category', App\Http\Controllers\Admin\ProductCategoryController::class);
        Route::resource('order',            App\Http\Controllers\Admin\OrderController::class);
        Route::resource('transaction',      App\Http\Controllers\Admin\TransactionController::class);

        Route::resource('shipping', App\Http\Controllers\Admin\ShippingController::class);
        Route::resource('shop-setting',     App\Http\Controllers\Admin\ShopSettingController::class);
        Route::resource('shipping-country', App\Http\Controllers\Admin\ShippingCountryController::class);
        Route::resource('coupon', App\Http\Controllers\Admin\CouponController::class);
        // Footer
        Route::resource('social-link',         App\Http\Controllers\Admin\SocialLinkController::class);
        Route::resource('footer-contact-item', App\Http\Controllers\Admin\FooterContactItemController::class);

        Route::resource('terms-of-use',      App\Http\Controllers\Admin\TermsOfUseController::class);
        Route::resource('privacy-policy',    App\Http\Controllers\Admin\PrivacyPolicyController::class);
        Route::resource('user-profile',      App\Http\Controllers\Admin\UserProfileController::class);
        Route::resource('users', App\Http\Controllers\Admin\UserController::class); 
    });
});

routes/web.php
use App\Http\Controllers\Frontend\UserPanelController;
use App\Http\Controllers\Frontend\Auth\UserLoginController;
use App\Http\Controllers\Frontend\Auth\UserRegisterController;
use App\Http\Controllers\Frontend\PaymentController;
use App\Http\Controllers\Frontend\PaypalController;
use App\Http\Controllers\Frontend\Auth\VerificationController;
use App\Http\Controllers\Frontend\SslCommerzPaymentController;
use App\Http\Controllers\User\MediaManagerController as UserMediaManagerController;
use App\Http\Controllers\User\TransactionController as UserTransactionController;
use App\Http\Controllers\User\UserOrderController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['XSS', 'HtmlSpecialchars']], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/email/verify', [VerificationController::class, 'show'])->name('verification.notice');
        Route::get('/email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify')->middleware(['signed']);
        Route::post('/email/resend', [VerificationController::class, 'resend'])->name('verification.resend');
    });
    // Frontend
    Route::get('/subscribe',                [App\Http\Controllers\Frontend\EmailTemplateController::class, 'subscription'])->name('subscribe');
    Route::get('/verify/{email}',                [App\Http\Controllers\Frontend\EmailTemplateController::class, 'verify'])->name('verify');

    Route::get('/',                     [DynamicPageController::class,  'index'])->name('home');
    Route::get('/about',                     [DynamicPageController::class,  'about'])->name('about');
    Route::get('/contact',                     [DynamicPageController::class,  'contact'])->name('contact');
    Route::get('/services',                     [DynamicPageController::class,  'services'])->name('services');
    Route::get('/signin',                     [DynamicPageController::class,  'signin'])->name('signin');
    Route::get('/term-condition',                     [DynamicPageController::class,  'termcondition'])->name('termcondition');
    Route::get('/faq',                     [DynamicPageController::class,  'faq'])->name('faq');
    Route::get('/privacy',                     [DynamicPageController::class,  'privacy'])->name('privacy');
    Route::get('/bloglist',                     [DynamicPageController::class,  'bloglist'])->name('bloglist');
    Route::get('/blog-details',                     [DynamicPageController::class,  'blogdetails'])->name('blogdetails');
    Route::get('/course/details/{slug}', [App\Http\Controllers\Frontend\CourseController::class,  'show'])->name('course.show');
    Route::get('/course', [App\Http\Controllers\Frontend\CourseController::class,  'index'])->name('course.index');

    //billing
    Route::get('/checkout',                     [App\Http\Controllers\Frontend\BillingController::class,  'checkout'])->middleware('auth')->name('checkout');
    Route::get('/coupon-apply',                     [App\Http\Controllers\Frontend\BillingController::class,  'couponapply'])->name('couponapply');
    Route::get('/cart-view',                     [App\Http\Controllers\Frontend\BillingController::class,  'cartview'])->name('cartview');
    Route::get('/add-to-cart',  [App\Http\Controllers\Frontend\BillingController::class, 'addcart'])->name('addcart');
    Route::get('/remove-from-cart', [App\Http\Controllers\Frontend\BillingController::class, 'removecart'])->name('removecart');
    Route::post('/proceed/checkout', [App\Http\Controllers\Frontend\BillingController::class, 'proceedcheckout'])->name('proceedcheckout');
    Route::group(['middleware' => ['auth', 'verified']], function() {
        Route::post('/freepurches', [App\Http\Controllers\Frontend\PaymentController::class,  'freepurches'])->name('freepurches');
        Route::get('/payment',                     [App\Http\Controllers\Frontend\BillingController::class,  'payment'])->name('payment');
    });
    Route::post('/placeorder', [App\Http\Controllers\Frontend\BillingController::class, 'placeorder'])->name('placeorder');

    Route::get('product/{slug}', [App\Http\Controllers\frontend\ProductController::class, 'show'])->name('product.show');
    Route::resource('/product', App\Http\Controllers\Frontend\ProductController::class);
    Route::get('/productsearch', [App\Http\Controllers\Frontend\ProductController::class, 'searchproduct'])->name('productsearch');
    Route::get('blog/{slug}', [App\Http\Controllers\frontend\BlogController::class, 'show'])->name('blog.show');
    Route::resource('blog', App\Http\Controllers\Frontend\BlogController::class);
    Route::post('blogcomment', [App\Http\Controllers\Frontend\BlogCommentController::class, 'store'])->name('blogcomment.store');
    Route::resource('contactmessage', App\Http\Controllers\Frontend\ContactMessageController::class);

    Route::get('cart-page',             [ShopController::class,     'cart_page'])->name('cart_page');
    // // Login Routes
    Route::get('login',                     [UserLoginController::class,  'userLoginForm'])->name('user.login');
    Route::post('/login',               [UserLoginController::class,    'userCheckLogin'])->name('user.login');
    Route::resource('registrations', UserRegisterController::class);
    Route::post('/logout',              [UserLoginController::class,    'userLogout'])->name('user.logout');
    Route::get('/forgot',               [ForgotPasswordController::class, 'forgot'])->name('user.forgot');
    Route::post('/forgot',              [ForgotPasswordController::class, 'resetLink'])->name('user.forgot');
    Route::get('/password-reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('user.reset');
    Route::post('/password-reset',      [ResetPasswordController::class, 'resetPassword'])->name('user.reset');
    Route::get('{slug}',                [DynamicPageController::class, 'page'])->name ('page');
 
    Route::group(['as' => 'user.','middleware' => ['auth', 'verified'], 'prefix' => 'user'], function () {
        Route::get('/mediamanager',         [UserMediaManagerController::class, 'index'])->name('mediamanager');
        Route::post('/mediamanager/upload', [UserMediaManagerController::class, 'upload'])->name('mediaupload');
        Route::get('/mediamanager/images',  [UserMediaManagerController::class, 'images'])->name('mediaimages');
        Route::get('/mediamanager/delete/', [UserMediaManagerController::class, 'delete'])->name('media.delete');
        Route::post('/productreview', [App\Http\Controllers\Frontend\ProductReviewController::class, 'store'])->name('productreview');
        Route::post('/coursereview', [App\Http\Controllers\Frontend\CourseReviewController::class, 'store'])->name('coursereview');
        Route::get('shop/cart',         [ShopController::class,      'cart'])->name('cart');
        Route::post('/update-profile',  [UserPanelController::class, 'update_profile'])->name('update');
        Route::post('/shipping-address',  [UserPanelController::class, 'shipping_address'])->name('shipping-address');
        Route::get('/dashboard',        [UserPanelController::class, 'dashboard'])->name('dashboard');
        Route::get('/profile',          [UserPanelController::class, 'profile'])->name('profile');
        Route::post('/updateprofile',  [UserPanelController::class, 'store'])->name('updateprofile'); 
        Route::post('/updateaddress',  [UserPanelController::class, 'update_address'])->name('updateaddress');
        Route::resource('order',            UserOrderController::class);
        Route::get('transactions',     [UserTransactionController::class, 'index'])->name('transactions');

        Route::post('/sslcommerz-pay',    [SslCommerzPaymentController::class, 'index'])->name('sslcommerz-pay');
        Route::post('/sslcommerz-pay-via-ajax', [SslCommerzPaymentController::class, 'payViaAjax'])->name('sslcommerz-pay-ajax');
        Route::post('/sslcommerz-success', [SslCommerzPaymentController::class,   'success'])->name('sslcommerz-success');
        Route::post('/sslcommerz-failed', [SslCommerzPaymentController::class,   'fail'])->name('sslcommerz-failed');
        Route::post('/sslcommerz-cancel', [SslCommerzPaymentController::class,   'cancel'])->name('sslcommerz-cancel');
        Route::post('/sslcommerz-ipn', [SslCommerzPaymentController::class, 'ipn'])->name('sslcommerz-ipn');

        Route::get('/pay-with-paypal',       [PaypalController::class,   'paypal_pay'])->name('pay-with-paypal');
        Route::get('/paypal-payment-success',       [PaypalController::class,   'paypal_success'])->name('paypal-payment-success');
        Route::get('/paypal-payment-cancled',       [PaypalController::class,   'paypal_cancel'])->name('paypal-payment-cancled');

        Route::post('/bank-pay',        [PaymentController::class,   'bank'])->name('bank-pay');
        Route::post('/stripe-pay',      [PaymentController::class,   'stripe'])->name('stripe-pay');
        Route::post('/razorpay-pay',    [PaymentController::class,   'razorpay'])->name('razorpay-pay');
        Route::post('/mollie-pay',      [PaymentController::class,   'mollie'])->name('mollie-pay');
        Route::get('/mollie-notify',    [PaymentController::class,   'mollie_notify'])->name('mollie-notify');
        Route::post('/instamojo-pay',   [PaymentController::class,   'instamojo'])->name('instamojo-pay');
        Route::get('/instamojo-verify', [PaymentController::class,   'instamojo_verify'])->name('instamojo-verify');
        Route::get('/paystack-pay',     [PaymentController::class,   'paystack'])->name('paystack-pay');
        Route::get('/flutterwave-pay', [PaymentController::class,   'flutterwave'])->name('flutterwave-pay');
        Route::get('/review/history/course', [UserPanelController::class, 'review_history_course'])->name('review.history.course');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    const DETAILS = 10;
    const ACTIVE = 1, CLOSE=0;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'image', 'slug', 'price', 'discount_price', 'description', 'sku', 'brand', 'weight', 'stock', 'category_id', 'status'];
    protected $table = 'products';

    public function getCategory()
    {
        return $this->hasOne(ProductCategory::class, 'id', 'category_id');
    }

    public function reviews()
    {
        return $this->hasMany(ProductReview::class, 'product_id', 'id');
    }

    public function orders()
    {
        return $this->hasMany(OrderItem::class, 'item_id', 'id');
    }


}

resources/views/admin/product/category/create.blade.php
@php
    $page_title = trans('Admin | Add product category');
@endphp
@extends('admin.layouts.master')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{{__('admin.Add Category')}}</h1>
            </div>
            <a class="btn btn-primary mb-4" href="{{URL::previous()}}" role="button"><i class="fas fa-arrow-circle-left"></i> {{trans('admin.Back')}}</a>
            <div class="section-body">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('admin.product-category.store')}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="">{{__('admin.Name')}}</label>
                                <input type="text" class="form-control" name="name">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block"  role="button"> {{trans('admin.Save')}} </button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/product/category/edit.blade.php
@php
    $page_title = trans('Admin | Edit product category');
@endphp
@extends('admin.layouts.master')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{{__('admin.Edit Category')}}</h1>
            </div>
            <a class="btn btn-primary mb-4" href="{{URL::previous()}}" role="button"><i class="fas fa-arrow-circle-left    "></i> {{trans('admin.Back')}}</a>
            <div class="section-body">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('admin.product-category.update', $category->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="">{{__('admin.Name')}}</label>
                                <input type="text" class="form-control" name="name" value="{{$category->name}}">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block"  role="button"> {{trans('admin.Save')}} </button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/product/category/index.blade.php
@php
$page_title = trans('Admin | Product categories');
@endphp
@extends('admin.layouts.master')
@section('content')
    {{-- Main Content --}}
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{{__('admin.Product Categories')}}</h1>
            </div>
            <a class="btn btn-primary mb-4" href="{{URL::previous()}}" role="button"><i class="fas fa-arrow-circle-left    "></i> {{trans('admin.Back')}}</a>
            <div class="section-body">
                <div class="card">
                    <div class="card-body  wsus_custom_overflow">
                        {{$dataTable->table()}}
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@push('script')
    {{$dataTable->scripts()}}
    <script>
        $(document).on('click', '.delete', function(e) {
            e.preventDefault();
            var url = $(this).attr('href');
            Swal.fire({
                title: '{{trans('admin.Are you sure?')}}',
                text: "{{trans('admin.You wont be able to revert this!')}}",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '{{trans('admin.Yes, delete it!')}}'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        success: function(response) {

                            if (response.status == 'success') {
                                Swal.fire(
                                    '{{trans('admin.Deleted!')}}',
                                    '{{trans('admin.Item has been deleted.')}}',
                                    '{{trans('admin.success')}}'
                                ).then((result) => {
                                    location.reload()
                                })
                            } else if (response.status == 'failed') {
                                toastr.warning(
                                    "{{trans('admin.Sorry, this category contains products!')}}"
                                )
                            }
                        }
                    });
                }
            })
        });
    </script>
@endpush